// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAg0qD-SVjq37Y4NegJFnURXGrJwWKhu88',
    appId: '1:914578425830:web:6702857d0f2817197ef827',
    messagingSenderId: '914578425830',
    projectId: 'inncampus-6731503090',
    authDomain: 'inncampus-6731503090.firebaseapp.com',
    storageBucket: 'inncampus-6731503090.firebasestorage.app',
    measurementId: 'G-MX6Z0BYB99',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhVcFEqG_tz7GM20rtQ3zEok92hXJhqxY',
    appId: '1:914578425830:android:380d005506c5771c7ef827',
    messagingSenderId: '914578425830',
    projectId: 'inncampus-6731503090',
    storageBucket: 'inncampus-6731503090.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDo1g5mxgp4DmMCQ8X19aHRywiLPKe_Obc',
    appId: '1:914578425830:ios:88f44c69a4e378ea7ef827',
    messagingSenderId: '914578425830',
    projectId: 'inncampus-6731503090',
    storageBucket: 'inncampus-6731503090.firebasestorage.app',
    iosBundleId: 'com.example.incampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDo1g5mxgp4DmMCQ8X19aHRywiLPKe_Obc',
    appId: '1:914578425830:ios:88f44c69a4e378ea7ef827',
    messagingSenderId: '914578425830',
    projectId: 'inncampus-6731503090',
    storageBucket: 'inncampus-6731503090.firebasestorage.app',
    iosBundleId: 'com.example.incampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAg0qD-SVjq37Y4NegJFnURXGrJwWKhu88',
    appId: '1:914578425830:web:58ccc3c945de28747ef827',
    messagingSenderId: '914578425830',
    projectId: 'inncampus-6731503090',
    authDomain: 'inncampus-6731503090.firebaseapp.com',
    storageBucket: 'inncampus-6731503090.firebasestorage.app',
    measurementId: 'G-FC6KYGMLM8',
  );
}
